spring.application.name=ScadaCR

scadacr.modbus.bootstrap.enabled=false
scadacr.modbus.bootstrap.identifier=modbus-device-1
scadacr.modbus.bootstrap.host=127.0.0.1
scadacr.modbus.bootstrap.port=502
scadacr.modbus.bootstrap.active=false
