spring.application.name=ScadaCR

scadacr.modbus.bootstrap.enabled=true
scadacr.modbus.bootstrap.identifier=arduino
scadacr.modbus.bootstrap.host=192.168.1.78
scadacr.modbus.bootstrap.port=502
scadacr.modbus.bootstrap.active=true
